seml:
  project_root_dir: ../../../..
  executable: seml/scripts/eval_pld_accounting.py
  conda_environment: timeseries_dp
  output_dir: /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/logs
  name: eval_pld_accounting

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:0
      mem: 128G          # memory
      cpus-per-task: 5  # num cores
      time: 00-01:00     # max time, D-HH:MM
      partition: cpu_all
      qos: deadline
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:0
      mem: 128G          # memory
      cpus-per-task: 5  # num cores
      time: 00-01:00     # max time, D-HH:MM
      partition: cpu_large
      qos: deadline

fixed:
  save_dir: /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/eval_pld_monotonicity_composed

  privacy_loss_kwargs:
    num_sequences: 320
    top_level_mode: sampling_poisson
    past_length: 14  # 2 weeks context
    future_length: 7  # 1 week forecast
    lead_time: 0
    min_past: 0
    min_future: 7  # Required for complete final forecast window
    noise_multiplier: 1.0
    tight_privacy_loss: True
    future_target_noise_multiplier: 0.0
    bottom_level_mode: sampling_poisson
  
  privacy_loss_kwargs.neighboring_relation:
    level: event
    size: 1
  
  epsilon_params:
    space: logspace
    start: -3.0
    stop: 3.0
    num: 20001
  
  max_epochs: null
  num_compositions: 100

  value_discretization_interval: 1e-3
  use_connect_dots: True

grid:
  privacy_loss_kwargs.min_sequence_length:
    type: choice
    options:
      - 27  # p_bad_bottom = 1.0
      - 48  # p_bad_bottom = 1 / 2
      - 216  # p_bad_bottom = 1 / 10

batch_size_32:
  fixed:
    privacy_loss_kwargs.batch_size: 32
  
  grid:
    privacy_loss_kwargs.instances_per_sequence:
      type: choice
      options:
        - 1
        - 2
        - 4
        - 8
        - 16

batch_size_160:
  fixed:
    privacy_loss_kwargs.batch_size: 160
  
  grid:
    privacy_loss_kwargs.instances_per_sequence:
      type: choice
      options:
        - 1
        - 2
        - 4
        - 8
        - 16
        #- 32

batch_size_320:
  fixed:
    privacy_loss_kwargs.batch_size: 320
  
  grid:
    privacy_loss_kwargs.instances_per_sequence:
      type: choice
      options:
        - 1
        - 2
        - 4
        - 8
        - 16
        #- 32
        #- 64
