seml:
  project_root_dir: ../../..
  executable: seml/scripts/traditional_baselines_standard_eval.py
  conda_environment: timeseries_dp
  output_dir: /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/logs
  name: trad_baselines_std_eval

slurm:
  - experiments_per_job: 5
    sbatch_options:
      gres: gpu:0
      mem: 256G          # memory
      cpus-per-task: 20  # num cores
      time: 07-00:00     # max time, D-HH:MM
      partition: cpu_large
      qos: deadline

fixed:
  save_dir: /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/traditional_baselines_standard_eval

grid:
  seed:
    type: choice
    options:
      - 0
      #- 1
      #- 2
      #- 3
      #- 4
  
  predictor_name:
    type: choice
    options:
      - SeasonalNaivePredictor
      - AutoARIMAPredictor
      - AutoETSPredictor
    
  use_season_length:
    type: choice
    options:
      - True
      - False

electricity:
  fixed:
    dataset_kwargs:
      dataset_name: electricity
      dataset_dir: /ceph/hdd/shared/schuchaj_gluonts_datasets

traffic:
  fixed:
    dataset_kwargs:
      dataset_name: traffic
      dataset_dir: /ceph/hdd/shared/schuchaj_gluonts_datasets

solar_10_minutes:
  fixed:
    dataset_kwargs:
      dataset_name: solar_10_minutes
      dataset_dir: /ceph/hdd/shared/schuchaj_gluonts_datasets