seml:
  project_root_dir: ../../../..
  executable: seml/scripts/eval_pld.py
  conda_environment: timeseries_dp
  output_dir: /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/logs
  name: eval_pld

slurm:
  - experiments_per_job: 4
    sbatch_options:
      gres: gpu:0
      mem: 64G          # memory
      cpus-per-task: 5  # num cores
      time: 00-01:00     # max time, D-HH:MM
      partition: cpu_all

fixed:
  save_dir: /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/eval_pld_monotonicity

  privacy_loss_kwargs:
    num_sequences: 320
    top_level_mode: sampling_without_replacement
    past_length: 1
    future_length: 1
    lead_time: 0
    min_past: 0
    min_future: 1
    noise_multiplier: 1.0
    tight_privacy_loss: True
    future_target_noise_multiplier: 0.0
    bottom_level_mode: sampling_with_replacement
  
  privacy_loss_kwargs.neighboring_relation:
    level: event
    size: 1
  
  epsilon_params:
    space: logspace
    start: -3.0
    stop: 3.0
    num: 20001
  
  value_discretization_interval: null
  use_connect_dots: True

grid:
  privacy_loss_kwargs.min_sequence_length:
    type: choice
    options:
      - 2  # rho = 1.0
      - 4  # rho = 1 / 2
      - 20  # rho = 1 / 10

batch_size_32:
  fixed:
    privacy_loss_kwargs.batch_size: 32
  
  grid:
    privacy_loss_kwargs.instances_per_sequence:
      type: choice
      options:
        - 1
        - 2
        - 4
        - 8
        - 16

batch_size_160:
  fixed:
    privacy_loss_kwargs.batch_size: 160
  
  grid:
    privacy_loss_kwargs.instances_per_sequence:
      type: choice
      options:
        - 1
        - 2
        - 4
        - 8
        - 16
        #- 32

batch_size_320:
  fixed:
    privacy_loss_kwargs.batch_size: 320
  
  grid:
    privacy_loss_kwargs.instances_per_sequence:
      type: choice
      options:
        - 1
        - 2
        - 4
        - 8
        - 16
        #- 32
        #- 64
